=== Shaman4eG/ITMO/1 course/1 semester/Informatics/lab2/schema_pockemons.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://msiter.ru" 
elementFormDefault="qualified">
<xs:element name="pokemons">
<xs:complexType>
<xs:sequence>
<xs:element name="group" maxOccurs="unbounded">
<xs:complexType mixed="true">
<xs:sequence>
<xs:element name="type">
<xs:complexType mixed="true">
<xs:sequence>
<xs:element name="species">
<xs:complexType mixed="true">
<xs:sequence>
<xs:element name="ability" type="xs:string"/>
<xs:element name="height">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:decimal">
<xs:attribute name="uom" type="xs:string"/>
</xs:extension>
</xs:simpleContent> 
</xs:complexType>
</xs:element>
<xs:element name="weight">
<xs:complexType>   
<xs:simpleContent>
<xs:extension base="xs:decimal">
<xs:attribute name="uom" type="xs:string"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="format" type="xs:string"/>
<xs:attribute name="release_year" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:schema>

=== Shaman4eG/ITMO/1 course/1 semester/Informatics/lab2/pokemons2.xml
<?xml version="1.0" encoding="utf-8"?>
<pokemons format="animation" release_year="1996"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://msiter.ru schema_pockemons.xsd">
<group name="physical">
<type name="poison">
<species name="Arbok">
<ability>Intimidate  </ability>
<height uom="meter">3.51  </height>
<weight uom="kg">65.0  </weight>
</species>  
</type>
</group>
<group name="special">
<type name="electric">
<species name="Pikachu">
<ability>Static  </ability>
<height uom="meter">0.41  </height>
<weight uom="kg">6.0  </weight>
</species>
</type>
</group>
<group name="mixed">
<type name="normal/flying">
<species name="Fearow">
<ability>Keen Eye  </ability>
<height uom="meter">1.19  </height>
<weight uom="kg">38.0  </weight>
</species>
</type>
</group>
</pokemons>

=== Shaman4eG/ITMO/1 course/1 semester/Informatics/lab3/pokemons_for_vba.xml
<?xml version="1.0" encoding="utf-8"?>
<pokemons format="animation" release_year="1996" xmlns="http://msiter.ru"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://msiter.ru schema_pockemons.xsd">
<species>
<!-- adfasd -->
<name><!-- adfasd -->Raticate</name>
<ability>Guts  </ability>
<height>0.71  </height>
<weight>18.5  </weight>
</species>
<!-- adfasd -->
<species>
<name>Charmander</name>
<ability>Blaze</ability>
<height>0.61</height>
<weight>8.5</weight>
</species>

<species>
<name>Bulbasaur</name>
<ability>Overgrow</ability>
<height>0.71</height>
<weight>6.9</weight>
</species>
</pokemons>
<!-- adfasd -->

=== Shaman4eG/ITMO/1 course/1 semester/Informatics/lab2/pokemons1.xml
<?xml version="1.0" encoding="utf-8"?>
<pokemons format="animation" release_year="1996" xmlns="http://msiter.ru" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://msiter.ru schema_pockemons.xsd">
<group name="physical">
<type name="normal">
<species name="Raticate">
<ability>Guts  </ability>
<height uom="meter">0.71  </height>
<weight uom="kg">18.5  </weight>
</species>
</type>     
</group>
<group name="special">
<type name="fire">
<species name="Charmander">
<ability>Blaze  </ability>
<height uom="meter">0.61  </height>
<weight uom="kg">8.5  </weight>
</species>
</type>
</group>
<group name="mixed">
<type name="grass/poison">
<species name="Bulbasaur">
<ability>Overgrow  </ability>
<height uom="meter">0.71  </height>
<weight uom="kg">6.9  </weight>
</species>
</type>
</group>
</pokemons>
